// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOgdWrzBhNPFiur0kZG4Q84n8BJgFQsaY',
    appId: '1:899641446431:android:b2bf7225d8bd0ba2a2452a',
    messagingSenderId: '899641446431',
    projectId: 'testapp-8ef1c',
    storageBucket: 'testapp-8ef1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlwyYPVmxD4LQ6ZXsNLZA9y8rQf7K-pgE',
    appId: '1:899641446431:ios:6b6a5002d1646461a2452a',
    messagingSenderId: '899641446431',
    projectId: 'testapp-8ef1c',
    storageBucket: 'testapp-8ef1c.appspot.com',
    androidClientId: '899641446431-0ms1vtc94iaenbm6jgi3fqso0miiutjo.apps.googleusercontent.com',
    iosClientId: '899641446431-vejqufmo69j2rvjhmlg88s53m5752h9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.bingo',
  );
}
